### ISSUE TITLE
Pull paypal sdk from central

### ISSUE THREAD

**Issue by ghost** [liveplayergames/UFP#1]
This app refrences the paypal sdk in settings.gradle, but doesnt included it. I looked around and most likely you just want to use `compile 'com.paypal.sdk:paypal-android-sdk:2.15.3'` in oyur main app.

**Comment by liveplayergames** [comment]
Oops... that was cruft from a different version/branch.
I cleaned it up. Let me know if anything else comes up.
Thanks,
David Rosen

**Comment by Rudloff** [comment]
Hello,

This was closed but I still see a `PayPalAndroidSDK-2.15.2.aar` file in the repository.
Unfortunately, we can't [include this app in F-Droid](https://gitlab.com/fdroid/rfp/issues/144) unless everything is built from source or pulled from a trusted repository like Maven Central.
